"use strict";
const app=document.getElementById("app");const esc=v=>String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const sectionNames={"reports":"Ежедневные отчеты","work-types":"Виды работ","marks":"Ведомость марок","schedule":"График работ","photos":"Фотографии объекта","scheme":"Монтажная схема","acted-days":"Актированные дни","penalties":"Штрафы","finance":"Финансы"};
function go(path){location.hash=path;}function mb(v){return (Number(v||0)/1048576).toFixed(1).replace(".",",");}
function updateDialogHtml(){return `<dialog id="updateDialog" class="update-dialog"><h2 id="updateTitle">Проверка обновления</h2><p id="updateText">Проверяем наличие новой версии...</p><div id="updateProgress" class="update-progress" hidden><div id="updateBar"></div></div><div id="updateActions" class="actions"></div></dialog>`;}
function showUpdate(){const d=document.getElementById("updateDialog");d.showModal();updateTitle.textContent="Проверка обновления";updateText.textContent="Проверяем наличие новой версии...";updateProgress.hidden=true;updateActions.innerHTML="";irProject.updater.check().catch(e=>showUpdateError(e.message));}
function showUpdateError(message){const d=document.getElementById("updateDialog");if(!d.open)d.showModal();updateTitle.textContent="Ошибка обновления";updateText.textContent=message||"Не удалось проверить обновление.";updateProgress.hidden=true;updateActions.innerHTML='<button id="updateClose">Закрыть</button>';updateClose.onclick=()=>d.close();}
irProject.updater.onStatus(status=>{const d=document.getElementById("updateDialog");if(!d)return;if(!d.open)d.showModal();if(status.type==="available"){updateTitle.textContent="Доступно обновление";updateText.textContent=`Доступна версия ${esc(status.version)}. Обновить IR Project?`;updateProgress.hidden=true;updateActions.innerHTML='<button id="updateNo">Нет</button><button id="updateYes">Да, обновить</button>';updateNo.onclick=()=>d.close();updateYes.onclick=()=>{updateTitle.textContent="Скачивание обновления";updateText.textContent="Подготовка к загрузке изменившихся блоков...";updateProgress.hidden=false;updateBar.style.width="0%";updateActions.innerHTML="";irProject.updater.download().catch(e=>showUpdateError(e.message));};}else if(status.type==="current"){updateTitle.textContent="Обновление не требуется";updateText.textContent="У вас установлена последняя версия IR Project.";updateProgress.hidden=true;updateActions.innerHTML='<button id="updateClose">Закрыть</button>';updateClose.onclick=()=>d.close();}else if(status.type==="progress"){updateTitle.textContent="Скачивание обновления";const size=status.total?`${mb(status.transferred)} МБ из ${mb(status.total)} МБ`:`${mb(status.transferred)} МБ`;updateText.textContent=`Загружено ${size} — ${status.percent}%`;updateProgress.hidden=false;updateBar.style.width=`${status.percent}%`;}else if(status.type==="downloaded"){updateTitle.textContent="Обновление готово";updateText.textContent=`Версия ${esc(status.version)} скачана. IR Project будет перезапущен для установки.`;updateProgress.hidden=true;updateActions.innerHTML='<button id="installUpdate">Установить и перезапустить</button>';installUpdate.onclick=()=>irProject.updater.install();}else if(status.type==="error")showUpdateError(status.message);});
async function objectsPage(){const objects=await irProject.objects.list();app.innerHTML=`<div class="page-head"><h1>Objects</h1><div class="head-actions"><button id="checkUpdate">Проверить обновление</button><button id="add">Добавить объект</button></div></div><div class="objects">${objects.map(o=>`<article data-object="${o.id}"><h2>${esc(o.name)}</h2><p>${esc(o.customer)}</p><p>${esc(o.address)}</p><strong>${esc(o.status)}</strong></article>`).join("")}</div><dialog id="formDialog"><form id="form"><h2>Добавить объект</h2><label>Название<input name="name" required></label><label>Заказчик<input name="customer" required></label><label>Адрес<input name="address" required></label><label>Статус<select name="status"><option>В работе</option><option>Завершен</option></select></label><label>Фото объекта<div><button type="button" id="photoButton">Выбрать</button><span id="photoName"></span></div></label><label>Баннер объекта<div><button type="button" id="bannerButton">Выбрать</button><span id="bannerName"></span></div></label><div class="actions"><button type="button" id="cancel">Отмена</button><button type="submit">Сохранить</button></div></form></dialog>${updateDialogHtml()}`;checkUpdate.onclick=showUpdate;document.querySelectorAll("[data-object]").forEach(x=>x.onclick=()=>go(`/objects/object/${x.dataset.object}`));let photo="",banner="";const d=formDialog;add.onclick=()=>d.showModal();cancel.onclick=()=>d.close();photoButton.onclick=async()=>{photo=await irProject.objects.selectImage();photoName.textContent=photo?photo.split(/[\\/]/).pop():""};bannerButton.onclick=async()=>{banner=await irProject.objects.selectImage();bannerName.textContent=banner?banner.split(/[\\/]/).pop():""};form.onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await irProject.objects.create({name:f.get("name"),customer:f.get("customer"),address:f.get("address"),status:f.get("status"),photo,banner});d.close();objectsPage();};}
async function objectPage(id){const o=await irProject.objects.get(id);if(!o)return go("/objects");const sections=await irProject.sections.get(id);app.innerHTML=`<button class="back" id="back">← Objects</button><h1>${esc(o.name)}</h1><div class="sections">${sections.map(s=>`<div class="section-row"><button class="section-link" data-section="${s.key}" ${s.enabled?"":"disabled"}>${esc(sectionNames[s.key])}</button><label class="toggle"><input type="checkbox" data-toggle="${s.key}" ${s.enabled?"checked":""}><span>${s.enabled?"Включен":"Отключен"}</span></label></div>`).join("")}</div>`;back.onclick=()=>go("/objects");document.querySelectorAll("[data-section]").forEach(x=>x.onclick=()=>go(`/objects/object/${id}/${x.dataset.section}`));document.querySelectorAll("[data-toggle]").forEach(x=>x.onchange=async()=>{await irProject.sections.set(id,x.dataset.toggle,x.checked);objectPage(id);});}
async function sectionPage(id,key){const o=await irProject.objects.get(id);if(!o||!sectionNames[key])return go("/objects");const sections=await irProject.sections.get(id),section=sections.find(x=>x.key===key);if(!section?.enabled)return go(`/objects/object/${id}`);app.innerHTML=`<button class="back" id="back">← ${esc(o.name)}</button><h1>${esc(sectionNames[key])}</h1>`;back.onclick=()=>go(`/objects/object/${id}`);}
async function render(){const route=location.hash.slice(1)||"/objects";if(route==="/objects")return objectsPage();let m=route.match(/^\/objects\/object\/(\d+)$/);if(m)return objectPage(m[1]);m=route.match(/^\/objects\/object\/(\d+)\/([^/]+)$/);if(m)return sectionPage(m[1],m[2]);go("/objects");}
window.addEventListener("hashchange",render);render();
