"use strict";
const app=document.getElementById("app");const esc=v=>String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const sectionNames={"reports":"Ежедневные отчеты","work-types":"Виды работ","marks":"Ведомость марок","schedule":"График работ","photos":"Фотографии объекта","scheme":"Монтажная схема","acted-days":"Актированные дни","penalties":"Штрафы","finance":"Финансы"};
function go(path){location.hash=path;}
async function objectsPage(){const objects=await irProject.objects.list();app.innerHTML=`<div class="page-head"><h1>Objects</h1><button id="add">Добавить объект</button></div><div class="objects">${objects.map(o=>`<article data-object="${o.id}"><h2>${esc(o.name)}</h2><p>${esc(o.customer)}</p><p>${esc(o.address)}</p><strong>${esc(o.status)}</strong></article>`).join("")}</div><dialog id="formDialog"><form id="form"><h2>Добавить объект</h2><label>Название<input name="name" required></label><label>Заказчик<input name="customer" required></label><label>Адрес<input name="address" required></label><label>Статус<select name="status"><option>В работе</option><option>Завершен</option></select></label><label>Фото объекта<div><button type="button" id="photoButton">Выбрать</button><span id="photoName"></span></div></label><label>Баннер объекта<div><button type="button" id="bannerButton">Выбрать</button><span id="bannerName"></span></div></label><div class="actions"><button type="button" id="cancel">Отмена</button><button type="submit">Сохранить</button></div></form></dialog>`;document.querySelectorAll("[data-object]").forEach(x=>x.onclick=()=>go(`/objects/object/${x.dataset.object}`));let photo="",banner="";const d=formDialog;add.onclick=()=>d.showModal();cancel.onclick=()=>d.close();photoButton.onclick=async()=>{photo=await irProject.objects.selectImage();photoName.textContent=photo?photo.split(/[\\/]/).pop():""};bannerButton.onclick=async()=>{banner=await irProject.objects.selectImage();bannerName.textContent=banner?banner.split(/[\\/]/).pop():""};form.onsubmit=async e=>{e.preventDefault();const f=new FormData(e.currentTarget);await irProject.objects.create({name:f.get("name"),customer:f.get("customer"),address:f.get("address"),status:f.get("status"),photo,banner});d.close();objectsPage();};}
async function objectPage(id){const o=await irProject.objects.get(id);if(!o)return go("/objects");const sections=await irProject.sections.get(id);app.innerHTML=`<button class="back" id="back">← Objects</button><h1>${esc(o.name)}</h1><div class="sections">${sections.map(s=>`<div class="section-row"><button class="section-link" data-section="${s.key}" ${s.enabled?"":"disabled"}>${esc(sectionNames[s.key])}</button><label class="toggle"><input type="checkbox" data-toggle="${s.key}" ${s.enabled?"checked":""}><span>${s.enabled?"Включен":"Отключен"}</span></label></div>`).join("")}</div>`;back.onclick=()=>go("/objects");document.querySelectorAll("[data-section]").forEach(x=>x.onclick=()=>go(`/objects/object/${id}/${x.dataset.section}`));document.querySelectorAll("[data-toggle]").forEach(x=>x.onchange=async()=>{await irProject.sections.set(id,x.dataset.toggle,x.checked);objectPage(id);});}
async function sectionPage(id,key){const o=await irProject.objects.get(id);if(!o||!sectionNames[key])return go("/objects");const sections=await irProject.sections.get(id),section=sections.find(x=>x.key===key);if(!section?.enabled)return go(`/objects/object/${id}`);app.innerHTML=`<button class="back" id="back">← ${esc(o.name)}</button><h1>${esc(sectionNames[key])}</h1>`;back.onclick=()=>go(`/objects/object/${id}`);}
async function render(){const route=location.hash.slice(1)||"/objects";if(route==="/objects")return objectsPage();let m=route.match(/^\/objects\/object\/(\d+)$/);if(m)return objectPage(m[1]);m=route.match(/^\/objects\/object\/(\d+)\/([^/]+)$/);if(m)return sectionPage(m[1],m[2]);go("/objects");}
window.addEventListener("hashchange",render);render();
