"use strict";
(()=>{
let profile={name:"",logo:""};
const esc=v=>String(v||"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
async function load(){try{profile=await irProject.company.get()||profile;await paintBrand()}catch(e){console.warn("Company profile:",e)}}
async function paintBrand(){const brand=document.querySelector(".brand");if(!brand)return;let logo="";if(profile.logo)try{logo=await irProject.images.read(profile.logo)}catch{}brand.innerHTML=`<div class="brand-mark company-logo">${logo?`<img src="${logo}" alt="">`:"IR"}</div><div><strong>${esc(profile.name||"IR Project")}</strong><span>Управление строительными объектами</span></div>`;brand.style.cursor="pointer";brand.title="Профиль компании";brand.onclick=open}
async function open(){let d=document.getElementById("companyDialog");if(!d){d=document.createElement("dialog");d.id="companyDialog";d.className="company-dialog";document.body.appendChild(d)}let pendingLogo=profile.logo||"";let logoUrl="";if(pendingLogo)try{logoUrl=await irProject.images.read(pendingLogo)}catch{};const draw=()=>{d.innerHTML=`<form id="companyForm"><div class="form-heading"><div><h2>Профиль компании</h2><p class="form-subtitle">Название и логотип компании для IR Project и документов</p></div><button type="button" class="dialog-x" id="companyClose">×</button></div><div class="company-profile-body"><div class="company-logo-editor" id="companyLogoPreview">${logoUrl?`<img src="${logoUrl}" alt="Логотип">`:`<span>Логотип</span>`}</div><div class="company-fields"><label>Название компании<input id="companyName" value="${esc(profile.name)}" placeholder="Например, ТОО «А-Темир Строй»" required></label><div><button type="button" class="ghost-btn" id="companyLogoButton">Выбрать логотип</button><p class="company-hint">PNG, JPG или WEBP. Лучше использовать логотип на прозрачном фоне.</p></div></div></div><div class="actions"><button type="button" id="companyCancel">Отмена</button><button type="submit" class="primary">Сохранить</button></div></form>`;d.querySelector("#companyClose").onclick=d.querySelector("#companyCancel").onclick=()=>d.close();d.querySelector("#companyLogoButton").onclick=async()=>{const x=await irProject.company.selectLogo();if(!x)return;pendingLogo=x;logoUrl=await irProject.images.read(x);draw()};d.querySelector("#companyForm").onsubmit=async e=>{e.preventDefault();profile=await irProject.company.save({name:d.querySelector("#companyName").value,logo:pendingLogo});d.close();paintBrand()}};draw();d.showModal()}
new MutationObserver(()=>paintBrand()).observe(document.documentElement,{childList:true,subtree:true});load();
})();
