"use strict";
const {app}=require("electron");
const {DatabaseSync}=require("node:sqlite");
const path=require("path");
let database;
const sectionKeys=["reports","work-types","marks","schedule","photos","scheme","acted-days","penalties","finance"];
function openDatabase(){database=new DatabaseSync(path.join(app.getPath("userData"),"ir-project.db"));database.exec(`PRAGMA foreign_keys=ON;
CREATE TABLE IF NOT EXISTS objects(id INTEGER PRIMARY KEY AUTOINCREMENT,name TEXT NOT NULL,customer TEXT NOT NULL,address TEXT NOT NULL,status TEXT NOT NULL CHECK(status IN ('В работе','Завершен')),photo TEXT NOT NULL DEFAULT '',banner TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS object_sections(object_id INTEGER NOT NULL,section_key TEXT NOT NULL,enabled INTEGER NOT NULL DEFAULT 1 CHECK(enabled IN(0,1)),PRIMARY KEY(object_id,section_key),FOREIGN KEY(object_id) REFERENCES objects(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS work_types(id INTEGER PRIMARY KEY AUTOINCREMENT,object_id INTEGER NOT NULL,name TEXT NOT NULL,project_code TEXT NOT NULL DEFAULT '',unit TEXT NOT NULL DEFAULT '',sort_order INTEGER NOT NULL DEFAULT 0,FOREIGN KEY(object_id) REFERENCES objects(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS reports(id INTEGER PRIMARY KEY AUTOINCREMENT,object_id INTEGER NOT NULL,report_date TEXT NOT NULL,data_json TEXT NOT NULL DEFAULT '{}',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,UNIQUE(object_id,report_date),FOREIGN KEY(object_id) REFERENCES objects(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS marks(id INTEGER PRIMARY KEY AUTOINCREMENT,object_id INTEGER NOT NULL,work_type_id INTEGER,project_code TEXT NOT NULL DEFAULT '',mark TEXT NOT NULL,name TEXT NOT NULL DEFAULT '',unit TEXT NOT NULL DEFAULT '',quantity REAL NOT NULL DEFAULT 0,volume REAL NOT NULL DEFAULT 0,mounted REAL NOT NULL DEFAULT 0,data_json TEXT NOT NULL DEFAULT '{}',FOREIGN KEY(object_id) REFERENCES objects(id) ON DELETE CASCADE,FOREIGN KEY(work_type_id) REFERENCES work_types(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS deliveries(id INTEGER PRIMARY KEY AUTOINCREMENT,object_id INTEGER NOT NULL,delivery_no TEXT NOT NULL DEFAULT '',delivery_date TEXT NOT NULL DEFAULT '',project_code TEXT NOT NULL DEFAULT '',total_volume REAL NOT NULL DEFAULT 0,data_json TEXT NOT NULL DEFAULT '{}',FOREIGN KEY(object_id) REFERENCES objects(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS object_photos(id INTEGER PRIMARY KEY AUTOINCREMENT,object_id INTEGER NOT NULL,report_id INTEGER,file_path TEXT NOT NULL,caption TEXT NOT NULL DEFAULT '',created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(object_id) REFERENCES objects(id) ON DELETE CASCADE,FOREIGN KEY(report_id) REFERENCES reports(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS schedule_items(id INTEGER PRIMARY KEY AUTOINCREMENT,object_id INTEGER NOT NULL,work_type_id INTEGER,title TEXT NOT NULL DEFAULT '',start_date TEXT NOT NULL DEFAULT '',end_date TEXT NOT NULL DEFAULT '',plan REAL NOT NULL DEFAULT 0,fact REAL NOT NULL DEFAULT 0,data_json TEXT NOT NULL DEFAULT '{}',FOREIGN KEY(object_id) REFERENCES objects(id) ON DELETE CASCADE,FOREIGN KEY(work_type_id) REFERENCES work_types(id) ON DELETE SET NULL);
CREATE TABLE IF NOT EXISTS acted_days(id INTEGER PRIMARY KEY AUTOINCREMENT,object_id INTEGER NOT NULL,day TEXT NOT NULL,reason TEXT NOT NULL DEFAULT '',data_json TEXT NOT NULL DEFAULT '{}',UNIQUE(object_id,day),FOREIGN KEY(object_id) REFERENCES objects(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS penalties(id INTEGER PRIMARY KEY AUTOINCREMENT,object_id INTEGER NOT NULL,penalty_date TEXT NOT NULL DEFAULT '',title TEXT NOT NULL DEFAULT '',amount REAL NOT NULL DEFAULT 0,data_json TEXT NOT NULL DEFAULT '{}',FOREIGN KEY(object_id) REFERENCES objects(id) ON DELETE CASCADE);
CREATE TABLE IF NOT EXISTS finance_entries(id INTEGER PRIMARY KEY AUTOINCREMENT,object_id INTEGER NOT NULL,entry_date TEXT NOT NULL DEFAULT '',entry_type TEXT NOT NULL DEFAULT '',title TEXT NOT NULL DEFAULT '',amount REAL NOT NULL DEFAULT 0,data_json TEXT NOT NULL DEFAULT '{}',FOREIGN KEY(object_id) REFERENCES objects(id) ON DELETE CASCADE);
CREATE INDEX IF NOT EXISTS idx_reports_object ON reports(object_id);CREATE INDEX IF NOT EXISTS idx_marks_object ON marks(object_id);CREATE INDEX IF NOT EXISTS idx_work_types_object ON work_types(object_id);CREATE INDEX IF NOT EXISTS idx_deliveries_object ON deliveries(object_id);CREATE INDEX IF NOT EXISTS idx_photos_object ON object_photos(object_id);CREATE INDEX IF NOT EXISTS idx_schedule_object ON schedule_items(object_id);CREATE INDEX IF NOT EXISTS idx_acted_object ON acted_days(object_id);CREATE INDEX IF NOT EXISTS idx_penalties_object ON penalties(object_id);CREATE INDEX IF NOT EXISTS idx_finance_object ON finance_entries(object_id);`);return database}
function closeDatabase(){if(database)database.close();database=undefined}
function listObjects(){return database.prepare("SELECT id,name,customer,address,status,photo,banner FROM objects ORDER BY id DESC").all()}
function getObject(id){return database.prepare("SELECT id,name,customer,address,status,photo,banner FROM objects WHERE id=?").get(id)||null}
function applySections(id,sections){if(!sections||typeof sections!=="object")return;const q=database.prepare("INSERT INTO object_sections(object_id,section_key,enabled) VALUES(?,?,?) ON CONFLICT(object_id,section_key) DO UPDATE SET enabled=excluded.enabled");for(const key of sectionKeys)if(Object.prototype.hasOwnProperty.call(sections,key))q.run(id,key,sections[key]?1:0)}
function createObject(data){const r=database.prepare("INSERT INTO objects(name,customer,address,status,photo,banner) VALUES(?,?,?,?,?,?)").run(data.name,data.customer,data.address,data.status,data.photo||"",data.banner||"");const id=Number(r.lastInsertRowid);for(const key of sectionKeys)database.prepare("INSERT INTO object_sections(object_id,section_key,enabled) VALUES(?,?,?)").run(id,key,data.sections?.[key]===false?0:1);return getObject(id)}
function updateObject(id,data){if(!getObject(id))return null;database.prepare("UPDATE objects SET name=?,customer=?,address=?,status=?,photo=?,banner=? WHERE id=?").run(data.name,data.customer,data.address,data.status,data.photo||"",data.banner||"",id);applySections(id,data.sections);return getObject(id)}
function deleteObject(id){return Number(database.prepare("DELETE FROM objects WHERE id=?").run(id).changes)>0}
function getSections(objectId){const saved=new Map(database.prepare("SELECT section_key,enabled FROM object_sections WHERE object_id=?").all(objectId).map(x=>[x.section_key,!!x.enabled]));return sectionKeys.map(key=>({key,enabled:saved.has(key)?saved.get(key):true}))}
function setSection(objectId,key,enabled){if(!sectionKeys.includes(key))throw Error("Unknown section");database.prepare("INSERT INTO object_sections(object_id,section_key,enabled) VALUES(?,?,?) ON CONFLICT(object_id,section_key) DO UPDATE SET enabled=excluded.enabled").run(objectId,key,enabled?1:0);return getSections(objectId)}
module.exports={openDatabase,closeDatabase,listObjects,getObject,createObject,updateObject,deleteObject,getSections,setSection};
