"use strict";
(()=>{
 const arr=v=>Array.isArray(v)?v:[];
 const esc=v=>String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
 const num=v=>{const n=Number(String(v??0).trim().replace(/\s/g,"").replace(",","."));return Number.isFinite(n)?n:0};
 const fmt=v=>{const n=num(v);return Number.isInteger(n)?String(n):String(Number(n.toFixed(4))).replace(".",",")};
 const norm=v=>String(v??"").trim().toLowerCase().replace(/\s+/g," ");
 const dmy=v=>{const p=String(v||"").slice(0,10).split("-");return p.length===3?`${p[2]}.${p[1]}.${p[0]}`:"—"};
 const record=r=>({id:String(r.id),record_type:r.record_type||"delivery",title:r.title||"",...(r.data||{})});
 const itemsOf=r=>{for(const k of ["items","marks","positions","rows"]){if(Array.isArray(r?.[k]))return r[k]}return[]};
 const svg=body=>`<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">${body}</svg>`;
 const editIcon=svg('<path d="M4 20h4L19 9l-4-4L4 16v4Z"/><path d="m13.5 6.5 4 4"/>');
 const trashIcon=svg('<path d="M4 7h16M9 7V4h6v3M7 7l1 13h8l1-13M10 11v5M14 11v5"/>');
 window.irDeliveriesPage=async oid=>{
  const app=document.getElementById("app"),root=irProject.data.forObject(oid),api=root.section("deliveries"),wtApi=root.section("work-types"),marksApi=root.section("marks"),object=await irProject.data.objects.get(oid);if(!object){location.hash="/objects";return}
  let [raw,workRows,markRows]=await Promise.all([api.list().catch(()=>[]),wtApi.list().catch(()=>[]),marksApi.list().catch(()=>[])]),selectedId="";
  const canEdit=()=>window.irAccess?window.irAccess.canEdit("deliveries"):false;
  const rows=()=>raw.map(record).sort((a,b)=>String(b.date||b.delivery_date||"").localeCompare(String(a.date||a.delivery_date||""))||Number(b.id)-Number(a.id));
  const workTypes=()=>arr(workRows).filter(r=>{const d=r.data||{},service=(d.accounting_type||"")==="service"||norm(d.unit)==="услуга";if(service||d.has_marks===false||d.work_category==="other")return false;if(d.has_marks===true||["installation","fabrication"].includes(d.work_category))return true;const id=String(r.id),name=norm(d.work_type||r.title||"");return name.includes("монтаж")||name.includes("изготов")||arr(markRows).some(m=>String(m.data?.work_type_id||"")===id)}).map(r=>{const d=r.data||{};return{id:String(r.id),name:d.work_type||r.title||"Без названия",code:d.project_code||"",unit:d.unit||""}});
  const serviceWorkIds=()=>new Set(arr(workRows).filter(r=>(r.data?.accounting_type||"")==="service"||norm(r.data?.unit)==="услуга").map(r=>String(r.id)));
  const isServiceItem=x=>x?.accounting_type==="service"||x?.is_service===true||norm(x?.unit)==="услуга"||serviceWorkIds().has(String(x?.work_type_id||""));
  const deliveryItems=r=>itemsOf(r).filter(x=>!isServiceItem(x));
  const marks=()=>arr(markRows).map(r=>({id:String(r.id),record_type:r.record_type||"item",title:r.title||"",...(r.data||{})}));
  const totalTonnage=()=>rows().reduce((s,x)=>s+num(x.total_tonnage??x.tonnage),0);
  const deliveredMap=excludeId=>{const map={};for(const r of rows()){if(excludeId&&String(r.id)===String(excludeId))continue;for(const x of deliveryItems(r)){const mid=String(x.mark_id||"");if(mid)map[mid]=(map[mid]||0)+num(x.qty??x.count??x.quantity)}}return map};
  const markState=(m,excludeId)=>{const total=num(m.qty??m.count),delivered=Math.min(total,deliveredMap(excludeId)[String(m.id)]||0),left=Math.max(0,total-delivered),uv=num(m.unit_volume??m.volume_one);return{total,delivered,left,uv}};
  const wtOptions=selected=>`<option value="">Выберите вид работы</option>${workTypes().map(w=>`<option value="${w.id}" ${String(selected||"")===w.id?"selected":""}>${esc(w.name)}${w.code?` · ${esc(w.code)}`:""}</option>`).join("")}`;
  const positionRow=x=>`<div class="delivery-position-row" data-initial-mark="${esc(x?.mark_id||"")}"><label class="dp-work">Вид работы<select name="work_type_id">${wtOptions(x?.work_type_id)}</select></label><label class="dp-code">Шифр<input name="project_code" readonly value="${esc(x?.project_code||"")}" placeholder="—"></label><label class="dp-mark">Марка из ведомости<div class="mark-picker"><input name="mark_search" autocomplete="off" value="${esc(x?.mark?`${x.mark}${x.name?" — "+x.name:""}`:"")}" placeholder="Поиск по марке или наименованию…"><input type="hidden" name="mark_id" value="${esc(x?.mark_id||"")}"><div class="mark-results" hidden></div></div><div class="selected-mark-balance" hidden></div></label><label class="dp-qty">Количество<input name="qty" inputmode="decimal" value="${esc(x?.qty??x?.count??"")}" placeholder="0"></label><label class="dp-volume">Объём<input name="volume" readonly value="${esc(x?.volume??x?.total_volume??"")}" placeholder="0"></label><label class="dp-unit">Ед.<input name="unit" readonly value="${esc(x?.unit||"")}" placeholder="—"></label><button type="button" class="delivery-position-remove row-remove" title="Удалить позицию">×</button></div>`;
  const composition=r=>{const items=deliveryItems(r);if(!items.length)return'<span class="delivery-composition-empty">Позиции не указаны</span>';const map=new Map();for(const x of items){const key=[x.work_type_id||x.work_type||"",x.project_code||""].join("|");if(!map.has(key))map.set(key,{name:x.work_type||"Работа",code:x.project_code||"",count:0});map.get(key).count++}const groups=[...map.values()];return `<div class="delivery-composition">${groups.slice(0,2).map(g=>`<div><b>${esc(g.name)}</b><span>${esc(g.code||"Шифр не указан")} · ${g.count} поз.</span></div>`).join("")}${groups.length>2?`<small>+ ещё ${groups.length-2}</small>`:""}</div>`};
  function dialogHtml(){return canEdit()?`<dialog id="deliveryDialog" class="delivery-dialog"><form id="deliveryForm"><input type="hidden" name="id"><div class="delivery-form-head"><div><h2 id="deliveryFormTitle">Добавить накладную</h2><p>Данные накладной и фактически привезённые марки</p></div><button type="button" id="deliveryDialogX" class="delivery-dialog-x">×</button></div><div class="delivery-form-grid delivery-main-fields"><label>Номер накладной<input name="number" required placeholder="Например: 154"></label><label>Дата<input type="date" name="date" required></label><label>Машина №<input name="vehicle_number" placeholder="Например: 777 ABC 09"></label><label>ФИО водителя<input name="driver_name" placeholder="ФИО водителя"></label><label class="wide">Общий тоннаж<input name="total_tonnage" inputmode="decimal" required placeholder="0,000"><small>Общий вес по накладной, тн</small></label></div><section class="delivery-positions"><div class="delivery-positions-head"><div><h3>Марки по накладной</h3><p>Вид работы → шифр → марка → количество</p></div><button type="button" id="deliveryAddPosition">＋ Добавить марку</button></div><div id="deliveryPositionsList" class="delivery-positions-list"></div></section><div class="delivery-form-actions"><button type="button" id="deliveryCancel">Отмена</button><button type="submit" class="primary">Сохранить</button></div></form></dialog>`:""}
  function list(){
   selectedId="";const all=rows();
   const body=all.length?all.map(r=>`<div class="delivery-row" data-delivery-id="${esc(r.id)}"><div><span>№</span><b>${esc(r.number||r.delivery_number||r.id)}</b></div><div><span>Дата</span><b>${dmy(r.date||r.delivery_date)}</b></div><div class="delivery-row-composition"><span>Вид работы · Шифр · Марки</span>${composition(r)}</div><div><span>Машина №</span><b>${esc(r.vehicle_number||"—")}</b></div><div><span>Водитель</span><b>${esc(r.driver_name||"—")}</b></div><div class="delivery-tonnage"><span>Общий тоннаж</span><b>${fmt(r.total_tonnage??r.tonnage)} тн</b></div>${canEdit()?`<div class="delivery-actions report-actions"><button type="button" data-delivery-edit="${esc(r.id)}" title="Редактировать">${editIcon}</button><button type="button" data-delivery-delete="${esc(r.id)}" class="report-delete" title="Удалить">${trashIcon}</button></div>`:"<div></div>"}</div>`).join(""):'<div class="delivery-empty">Раздел Поставки пуст</div>';
   app.innerHTML=`<div class="deliveries-page"><div class="deliveries-head"><button class="back" id="deliveriesBack">← Назад</button><div><h1>Поставки</h1><p>${esc(object.name||"")}</p></div>${canEdit()?'<button class="delivery-add" id="deliveryAdd">＋ Добавить накладную</button>':""}</div><div class="delivery-summary"><div><span>Накладных</span><b>${all.length}</b></div><div><span>Общий тоннаж</span><b>${fmt(totalTonnage())} тн</b></div><div><span>Последняя поставка</span><b>${all.length?dmy(all[0].date||all[0].delivery_date):"—"}</b></div></div><div class="delivery-card"><div class="delivery-table-head"><span>Номер</span><span>Дата</span><span>Вид работы · Шифр · Марки</span><span>Машина №</span><span>Водитель</span><span>Тоннаж</span><span></span></div><div class="delivery-list">${body}</div></div>${dialogHtml()}</div>`;
   document.getElementById("deliveriesBack").onclick=()=>location.hash=`/objects/object/${oid}`;
   document.querySelectorAll("[data-delivery-id]").forEach(row=>row.onclick=e=>{if(e.target.closest(".delivery-actions"))return;detail(row.dataset.deliveryId)});
   if(canEdit())setupDialog();
  }
  function detail(id){
   selectedId=String(id);const r=rows().find(x=>String(x.id)===selectedId);if(!r)return list();const items=deliveryItems(r);
   const tableRows=items.length?items.map(x=>`<tr><td><b>${esc(x.work_type||"Работа")}</b></td><td>${esc(x.project_code||"—")}</td><td><b>${esc(x.mark||"—")}</b>${x.name?`<small>${esc(x.name)}</small>`:""}</td><td>${fmt(x.qty??x.count)}</td><td><b>${fmt(x.volume??x.total_volume)} ${esc(x.unit||"")}</b></td></tr>`).join(""):'<tr><td colspan="5" class="delivery-detail-empty">Позиции по маркам не указаны</td></tr>';
   app.innerHTML=`<div class="deliveries-page"><div class="deliveries-head"><button class="back" id="deliveryDetailBack">← К накладным</button><div><h1>Накладная №${esc(r.number||r.delivery_number||r.id)}</h1><p>${esc(object.name||"")}</p></div>${canEdit()?`<div class="delivery-detail-actions report-actions"><button id="deliveryDetailEdit" title="Редактировать">${editIcon}</button><button id="deliveryDetailDelete" class="report-delete" title="Удалить">${trashIcon}</button></div>`:""}</div><div class="delivery-detail-card"><div class="delivery-detail-title"><span>ПОСТАВКА</span><h2>Накладная №${esc(r.number||r.delivery_number||r.id)}</h2><p>от ${dmy(r.date||r.delivery_date)}</p></div><div class="delivery-detail-grid"><div><span>Номер накладной</span><b>${esc(r.number||r.delivery_number||r.id)}</b></div><div><span>Дата</span><b>${dmy(r.date||r.delivery_date)}</b></div><div><span>Машина №</span><b>${esc(r.vehicle_number||"—")}</b></div><div><span>ФИО водителя</span><b>${esc(r.driver_name||"—")}</b></div><div><span>Позиций</span><b>${items.length}</b></div><div class="accent"><span>Общий тоннаж</span><b>${fmt(r.total_tonnage??r.tonnage)} тн</b></div></div><section class="delivery-items-section"><div class="delivery-items-title"><h3>Марки по накладной</h3><span>${items.length} поз.</span></div><div class="delivery-items-table"><table><thead><tr><th>Вид работы</th><th>Шифр</th><th>Марка</th><th>Кол-во</th><th>Объём</th></tr></thead><tbody>${tableRows}</tbody></table></div></section></div>${dialogHtml()}</div>`;
   document.getElementById("deliveryDetailBack").onclick=list;
   if(canEdit()){setupDialog();document.getElementById("deliveryDetailEdit").onclick=()=>openDialog(r);document.getElementById("deliveryDetailDelete").onclick=()=>remove(r)}
  }
  function setupPositionRow(row,editId){
   const wt=row.querySelector('[name="work_type_id"]'),code=row.querySelector('[name="project_code"]'),unit=row.querySelector('[name="unit"]'),search=row.querySelector('[name="mark_search"]'),mid=row.querySelector('[name="mark_id"]'),qty=row.querySelector('[name="qty"]'),volume=row.querySelector('[name="volume"]'),box=row.querySelector('.mark-results'),balance=row.querySelector('.selected-mark-balance');let selected=marks().find(m=>String(m.id)===String(mid.value));
   const showBalance=()=>{if(!selected){balance.hidden=true;return}const s=markState(selected,editId);balance.innerHTML=`<span>Всего: <b>${fmt(s.total)}</b></span><span class="mounted">Завезено: <b>${fmt(s.delivered)}</b></span><span class="left">Осталось: <b>${fmt(s.left)}</b></span>`;balance.hidden=false;qty.max=String(s.left)};
   const calc=()=>{if(!selected){volume.value="0";return}const s=markState(selected,editId),q=Math.max(0,num(qty.value));if(q>s.left)qty.value=fmt(s.left);volume.value=fmt(num(qty.value)*s.uv)};
   const renderMarks=()=>{const wid=String(wt.value),q=search.value.trim().toLowerCase();if(!wid){box.innerHTML='<div class="mark-result-empty">Сначала выберите вид работы</div>';box.hidden=false;return}const list=marks().filter(m=>String(m.work_type_id||"")===wid&&(!q||`${m.mark||m.title||""} ${m.name||""}`.toLowerCase().includes(q))).sort((a,b)=>String(a.mark||a.title||"").localeCompare(String(b.mark||b.title||""),"ru",{numeric:true}));box.innerHTML=list.length?list.map(m=>{const s=markState(m,editId),done=s.left<=0;return `<button type="button" data-mid="${m.id}" class="${done?"mark-result-done":s.delivered>0?"mark-result-partial":"mark-result-left"}" ${done?'disabled title="Марка завезена полностью"':""}><b>${esc(m.mark||m.title||"—")}</b><span>${esc(m.name||"")}</span><i>Всего ${fmt(s.total)} · Завезено ${fmt(s.delivered)} · Ост. ${fmt(s.left)}</i></button>`}).join(""):'<div class="mark-result-empty">Марки не найдены</div>';box.hidden=false;box.querySelectorAll("button:not(:disabled)[data-mid]").forEach(b=>b.onclick=()=>{selected=marks().find(m=>String(m.id)===String(b.dataset.mid));mid.value=selected.id;search.value=`${selected.mark||selected.title||""}${selected.name?" — "+selected.name:""}`;box.hidden=true;showBalance();calc()})};
   wt.onchange=()=>{const w=workTypes().find(x=>x.id===String(wt.value));code.value=w?.code||"";unit.value=w?.unit||"";selected=null;mid.value="";search.value="";qty.value="";volume.value="";balance.hidden=true;box.hidden=true};
   search.onfocus=renderMarks;search.oninput=()=>{selected=null;mid.value="";balance.hidden=true;renderMarks()};qty.oninput=calc;row.querySelector('.delivery-position-remove').onclick=()=>row.remove();showBalance();calc();
  }
  function setupDialog(){
   const d=document.getElementById("deliveryDialog"),f=document.getElementById("deliveryForm"),listEl=document.getElementById("deliveryPositionsList");if(!d||!f||!listEl)return;
   document.getElementById("deliveryAdd")?.addEventListener("click",()=>openDialog());
   document.getElementById("deliveryDialogX").onclick=()=>d.close();document.getElementById("deliveryCancel").onclick=()=>d.close();
   document.getElementById("deliveryAddPosition").onclick=()=>{listEl.insertAdjacentHTML("beforeend",positionRow({}));setupPositionRow(listEl.lastElementChild,String(f.elements.id.value||""))};
   document.querySelectorAll("[data-delivery-edit]").forEach(b=>b.onclick=e=>{e.stopPropagation();openDialog(rows().find(x=>String(x.id)===String(b.dataset.deliveryEdit)))});
   document.querySelectorAll("[data-delivery-delete]").forEach(b=>b.onclick=e=>{e.stopPropagation();const r=rows().find(x=>String(x.id)===String(b.dataset.deliveryDelete));if(r)remove(r)});
   f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f),id=String(fd.get("id")||""),number=String(fd.get("number")||"").trim(),date=String(fd.get("date")||""),vehicle=String(fd.get("vehicle_number")||"").trim(),driver=String(fd.get("driver_name")||"").trim(),tonnage=num(fd.get("total_tonnage"));if(!number||!date)return;if(tonnage<0)return alert("Общий тоннаж не может быть отрицательным.");const items=[...f.querySelectorAll('.delivery-position-row')].map(row=>{const wid=String(row.querySelector('[name="work_type_id"]').value),w=workTypes().find(x=>x.id===wid),mid=String(row.querySelector('[name="mark_id"]').value),m=marks().find(x=>String(x.id)===mid),q=num(row.querySelector('[name="qty"]').value),uv=num(m?.unit_volume??m?.volume_one);return{work_type_id:wid,work_type:w?.name||"",project_code:w?.code||"",unit:w?.unit||m?.unit||"",mark_id:mid,mark:m?.mark||m?.title||"",name:m?.name||"",qty:q,unit_volume:uv,volume:q*uv}}).filter(x=>x.work_type_id&&x.mark_id&&x.qty>0);if(!items.length)return alert("Добавьте хотя бы одну марку в накладную.");const byMark={};for(const x of items)byMark[x.mark_id]=(byMark[x.mark_id]||0)+num(x.qty);for(const [mid,q] of Object.entries(byMark)){const m=marks().find(x=>String(x.id)===String(mid)),s=m?markState(m,id):null;if(s&&q>s.left+1e-9)return alert(`По марке ${m.mark||m.title||""} осталось ${fmt(s.left)}, а в накладной указано ${fmt(q)}.`)}const duplicate=rows().find(x=>String(x.id)!==id&&String(x.number||x.delivery_number||"").trim().toLowerCase()===number.toLowerCase());if(duplicate&&!confirm(`Накладная №${number} уже существует. Всё равно сохранить?`))return;const payload={record_type:"delivery",title:`Накладная №${number}`,data:{number,date,vehicle_number:vehicle,driver_name:driver,total_tonnage:tonnage,items}};if(id)await api.update(id,payload);else await api.create(payload);raw=await api.list().catch(()=>raw);d.close();if(selectedId&&id===selectedId)detail(id);else list()};
  }
  function openDialog(r){
   const d=document.getElementById("deliveryDialog"),f=document.getElementById("deliveryForm"),listEl=document.getElementById("deliveryPositionsList");if(!d||!f||!listEl)return;f.reset();const editId=String(r?.id||"");f.elements.id.value=editId;f.elements.number.value=r?.number||r?.delivery_number||"";f.elements.date.value=String(r?.date||r?.delivery_date||"").slice(0,10);f.elements.vehicle_number.value=r?.vehicle_number||"";f.elements.driver_name.value=r?.driver_name||"";f.elements.total_tonnage.value=r?fmt(r.total_tonnage??r.tonnage):"";const items=deliveryItems(r||{});listEl.innerHTML=(items.length?items:[{}]).map(positionRow).join("");listEl.querySelectorAll('.delivery-position-row').forEach(row=>setupPositionRow(row,editId));document.getElementById("deliveryFormTitle").textContent=r?"Редактировать накладную":"Добавить накладную";d.showModal()
  }
  async function remove(r){if(!confirm(`Удалить накладную №${r.number||r.delivery_number||r.id}?`))return;await api.remove(r.id);raw=await api.list().catch(()=>[]);list()}
  list();
 };
 const direct=location.hash.match(/^#?\/objects\/object\/(\d+)\/deliveries$/);if(direct)setTimeout(()=>window.irDeliveriesPage(direct[1]),0);
})();
