"use strict";
(()=>{
 const esc=v=>String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
 const num=v=>{const n=Number(String(v??0).trim().replace(/\s/g,"").replace(",","."));return Number.isFinite(n)?n:0};
 const fmt=v=>{const n=num(v);return Number.isInteger(n)?String(n):String(Number(n.toFixed(4))).replace(".",",")};
 const dmy=v=>{const p=String(v||"").slice(0,10).split("-");return p.length===3?`${p[2]}.${p[1]}.${p[0]}`:"—"};
 const record=r=>({id:String(r.id),record_type:r.record_type||"delivery",title:r.title||"",...(r.data||{})});
 window.irDeliveriesPage=async oid=>{
  const app=document.getElementById("app"),root=irProject.data.forObject(oid),api=root.section("deliveries"),object=await irProject.data.objects.get(oid);if(!object){location.hash="/objects";return}
  let raw=await api.list().catch(()=>[]),selectedId="";
  const canEdit=()=>window.irAccess?window.irAccess.canEdit("deliveries"):false;
  const rows=()=>raw.map(record).sort((a,b)=>String(b.date||b.delivery_date||"").localeCompare(String(a.date||a.delivery_date||""))||Number(b.id)-Number(a.id));
  const totalTonnage=()=>rows().reduce((s,x)=>s+num(x.total_tonnage??x.tonnage),0);
  function dialogHtml(){return canEdit()?`<dialog id="deliveryDialog" class="delivery-dialog"><form id="deliveryForm"><input type="hidden" name="id"><div class="delivery-form-head"><div><h2 id="deliveryFormTitle">Добавить накладную</h2><p>Основные данные поставки на объект</p></div><button type="button" id="deliveryDialogX" class="delivery-dialog-x">×</button></div><div class="delivery-form-grid"><label>Номер накладной<input name="number" required placeholder="Например: 154"></label><label>Дата<input type="date" name="date" required></label><label class="wide">Вид марок<input name="mark_type" required placeholder="Например: Металлоконструкции"></label><label>Машина №<input name="vehicle_number" placeholder="Например: 777 ABC 09"></label><label>ФИО водителя<input name="driver_name" placeholder="ФИО водителя"></label><label class="wide">Общий тоннаж<input name="total_tonnage" inputmode="decimal" required placeholder="0,000"><small>Единица измерения: тн</small></label></div><div class="delivery-form-actions"><button type="button" id="deliveryCancel">Отмена</button><button type="submit" class="primary">Сохранить</button></div></form></dialog>`:""}
  function list(){
   selectedId="";const all=rows();
   const body=all.length?all.map((r,i)=>`<div class="delivery-row" data-delivery-id="${esc(r.id)}"><div><span>№</span><b>${esc(r.number||r.delivery_number||r.id)}</b></div><div><span>Дата</span><b>${dmy(r.date||r.delivery_date)}</b></div><div><span>Вид марок</span><b>${esc(r.mark_type||"—")}</b></div><div><span>Машина №</span><b>${esc(r.vehicle_number||"—")}</b></div><div><span>Водитель</span><b>${esc(r.driver_name||"—")}</b></div><div class="delivery-tonnage"><span>Общий тоннаж</span><b>${fmt(r.total_tonnage??r.tonnage)} тн</b></div>${canEdit()?`<div class="delivery-actions"><button type="button" data-delivery-edit="${esc(r.id)}" title="Редактировать">✎</button><button type="button" data-delivery-delete="${esc(r.id)}" class="danger" title="Удалить">⌫</button></div>`:"<div></div>"}</div>`).join(""):'<div class="delivery-empty">Раздел Поставки пуст</div>';
   app.innerHTML=`<div class="deliveries-page"><div class="deliveries-head"><button class="back" id="deliveriesBack">← Назад</button><div><h1>Поставки</h1><p>${esc(object.name||"")}</p></div>${canEdit()?'<button class="delivery-add" id="deliveryAdd">＋ Добавить накладную</button>':""}</div><div class="delivery-summary"><div><span>Накладных</span><b>${all.length}</b></div><div><span>Общий тоннаж</span><b>${fmt(totalTonnage())} тн</b></div><div><span>Последняя поставка</span><b>${all.length?dmy(all[0].date||all[0].delivery_date):"—"}</b></div></div><div class="delivery-card"><div class="delivery-table-head"><span>Номер</span><span>Дата</span><span>Вид марок</span><span>Машина №</span><span>Водитель</span><span>Тоннаж</span><span></span></div><div class="delivery-list">${body}</div></div>${dialogHtml()}</div>`;
   document.getElementById("deliveriesBack").onclick=()=>location.hash=`/objects/object/${oid}`;
   document.querySelectorAll("[data-delivery-id]").forEach(row=>row.onclick=e=>{if(e.target.closest(".delivery-actions"))return;detail(row.dataset.deliveryId)});
   if(canEdit())setupDialog();
  }
  function detail(id){
   selectedId=String(id);const r=rows().find(x=>String(x.id)===selectedId);if(!r)return list();
   app.innerHTML=`<div class="deliveries-page"><div class="deliveries-head"><button class="back" id="deliveryDetailBack">← К накладным</button><div><h1>Накладная №${esc(r.number||r.delivery_number||r.id)}</h1><p>${esc(object.name||"")}</p></div>${canEdit()?`<div class="delivery-detail-actions"><button id="deliveryDetailEdit">Редактировать</button><button id="deliveryDetailDelete" class="danger">Удалить</button></div>`:""}</div><div class="delivery-detail-card"><div class="delivery-detail-title"><span>ПОСТАВКА</span><h2>Накладная №${esc(r.number||r.delivery_number||r.id)}</h2><p>от ${dmy(r.date||r.delivery_date)}</p></div><div class="delivery-detail-grid"><div><span>Номер накладной</span><b>${esc(r.number||r.delivery_number||r.id)}</b></div><div><span>Дата</span><b>${dmy(r.date||r.delivery_date)}</b></div><div><span>Вид марок</span><b>${esc(r.mark_type||"—")}</b></div><div><span>Машина №</span><b>${esc(r.vehicle_number||"—")}</b></div><div><span>ФИО водителя</span><b>${esc(r.driver_name||"—")}</b></div><div class="accent"><span>Общий тоннаж</span><b>${fmt(r.total_tonnage??r.tonnage)} тн</b></div></div></div>${dialogHtml()}</div>`;
   document.getElementById("deliveryDetailBack").onclick=list;
   if(canEdit()){setupDialog();document.getElementById("deliveryDetailEdit").onclick=()=>openDialog(r);document.getElementById("deliveryDetailDelete").onclick=()=>remove(r)}
  }
  function setupDialog(){
   const d=document.getElementById("deliveryDialog"),f=document.getElementById("deliveryForm");if(!d||!f)return;
   window.__irOpenDeliveryDialog=r=>openDialog(r);
   document.getElementById("deliveryAdd")?.addEventListener("click",()=>openDialog());
   document.getElementById("deliveryDialogX").onclick=()=>d.close();document.getElementById("deliveryCancel").onclick=()=>d.close();
   document.querySelectorAll("[data-delivery-edit]").forEach(b=>b.onclick=e=>{e.stopPropagation();openDialog(rows().find(x=>String(x.id)===String(b.dataset.deliveryEdit)))});
   document.querySelectorAll("[data-delivery-delete]").forEach(b=>b.onclick=e=>{e.stopPropagation();const r=rows().find(x=>String(x.id)===String(b.dataset.deliveryDelete));if(r)remove(r)});
   f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f),id=String(fd.get("id")||""),number=String(fd.get("number")||"").trim(),date=String(fd.get("date")||""),markType=String(fd.get("mark_type")||"").trim(),vehicle=String(fd.get("vehicle_number")||"").trim(),driver=String(fd.get("driver_name")||"").trim(),tonnage=num(fd.get("total_tonnage"));if(!number||!date||!markType)return;if(tonnage<0)return alert("Общий тоннаж не может быть отрицательным.");const duplicate=rows().find(x=>String(x.id)!==id&&String(x.number||x.delivery_number||"").trim().toLowerCase()===number.toLowerCase());if(duplicate&&!confirm(`Накладная №${number} уже существует. Всё равно сохранить?`))return;const payload={record_type:"delivery",title:`Накладная №${number}`,data:{number,date,mark_type:markType,vehicle_number:vehicle,driver_name:driver,total_tonnage:tonnage}};if(id)await api.update(id,payload);else await api.create(payload);raw=await api.list().catch(()=>raw);d.close();if(selectedId&&id===selectedId)detail(id);else list()};
  }
  function openDialog(r){const d=document.getElementById("deliveryDialog"),f=document.getElementById("deliveryForm");if(!d||!f)return;f.reset();f.elements.id.value=r?.id||"";f.elements.number.value=r?.number||r?.delivery_number||"";f.elements.date.value=String(r?.date||r?.delivery_date||"").slice(0,10);f.elements.mark_type.value=r?.mark_type||"";f.elements.vehicle_number.value=r?.vehicle_number||"";f.elements.driver_name.value=r?.driver_name||"";f.elements.total_tonnage.value=r?fmt(r.total_tonnage??r.tonnage):"";document.getElementById("deliveryFormTitle").textContent=r?"Редактировать накладную":"Добавить накладную";d.showModal()}
  async function remove(r){if(!confirm(`Удалить накладную №${r.number||r.delivery_number||r.id}?`))return;await api.remove(r.id);raw=await api.list().catch(()=>[]);list()}
  list();
 };
})();
