"use strict";
window.irFinancePage=async function(objectId){
 const oid=String(objectId||"");if(!oid)return;
 const app=document.getElementById("app"),root=irProject.data.forObject(oid),api=root.section("finance"),wtApi=root.section("work-types"),marksApi=root.section("marks"),object=await irProject.data.objects.get(oid);
 if(!object){location.hash="/objects";return}
 const canEdit=()=>window.irAccess?window.irAccess.canEdit("finance"):false;
 const arr=v=>Array.isArray(v)?v:[];
 const esc=v=>String(v??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
 const num=v=>{const n=Number(String(v??"").trim().replace(/\s/g,"").replace(",","."));return Number.isFinite(n)?n:0};
 const fmt=v=>{const n=num(v);return Number.isInteger(n)?n.toLocaleString("ru-RU"):Number(n.toFixed(4)).toLocaleString("ru-RU",{maximumFractionDigits:4})};
 const money=v=>Math.round(num(v)).toLocaleString("ru-RU")+" тг";
 const dmy=v=>{const s=String(v||"").slice(0,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(s))return s||"—";const[y,m,d]=s.split("-");return d+"."+m+"."+y};
 const norm=v=>String(v??"").trim().toLowerCase().replace(/\s+/g," ");
 const markTotal=x=>{const d=x?.data||x||{},raw=d.total_value??d.total_volume;if(raw!==undefined&&raw!==null&&String(raw).trim()!=="")return num(raw);return num(d.qty??d.count)*num(d.unit_volume??d.volume_one)};
 const docTypeText=t=>t==="invoice"?"Накладная":"АВР";
 let [financeRows,workRows,markRows]=await Promise.all([api.list().catch(()=>[]),wtApi.list().catch(()=>[]),marksApi.list().catch(()=>[])]);
 const rec=r=>({id:r.id,record_type:r.record_type||"",title:r.title||"",...(r.data||{})});
 const finance=()=>financeRows.map(rec);
 const rateRows=()=>finance().filter(x=>x.record_type==="finance_rate");
 const documents=()=>finance().filter(x=>x.record_type==="finance_document").sort((a,b)=>String(b.date||"").localeCompare(String(a.date||""))||Number(b.id)-Number(a.id));
 const workTypes=()=>workRows.map(r=>{const d=r.data||{},id=String(r.id),unit=d.accounting_type==="service"||norm(d.unit)==="услуга"?"услуга":String(d.unit||""),service=unit==="услуга",marked=!service&&(d.has_marks===true||["installation","fabrication"].includes(d.work_category)||(!d.work_category&&d.has_marks!==false&&arr(markRows).some(m=>String(m.data?.work_type_id||"")===id))),workPlan=num(d.planned_volume??d.plan_volume),marksPlan=markRows.filter(m=>String(m.data?.work_type_id||"")===id).reduce((s,m)=>s+markTotal(m),0),plan=service?1:Math.max(workPlan,marksPlan);return{id,name:d.work_type||r.title||"Без названия",code:d.project_code||"",unit,service,marked,workPlan,marksPlan,plan}});
 const rateFor=id=>rateRows().find(r=>String(r.work_type_id||"")===String(id));
 const docItems=(excludeId="")=>documents().filter(d=>String(d.id)!==String(excludeId)).flatMap(d=>arr(d.items));
 const closedQty=(wid,excludeId="")=>docItems(excludeId).filter(x=>String(x.work_type_id||"")===String(wid)).reduce((s,x)=>s+num(x.qty),0);
 const closedAmount=wid=>documents().flatMap(d=>arr(d.items)).filter(x=>String(x.work_type_id||"")===String(wid)).reduce((s,x)=>s+num(x.amount??num(x.qty)*num(x.price)),0);
 const totalDoc=d=>arr(d.items).reduce((s,x)=>s+num(x.amount??num(x.qty)*num(x.price)),0);
 function rateDialog(){if(!canEdit())return"";return`<dialog id="financeRateDialog" class="finance-dialog finance-rate-dialog"><form id="financeRateForm" novalidate><input type="hidden" name="id"><input type="hidden" name="work_type_id"><div class="finance-form-head"><div><h2>Договорная расценка</h2><p id="financeRateWork"></p></div><button type="button" class="finance-x" id="financeRateX">×</button></div><div class="finance-rate-grid"><label>Цена за 1 ед., тг<input name="price" inputmode="decimal" required placeholder="Например: 240 000"></label><label>Закрывается документом<select name="closing_type"><option value="avr">Акт выполненных работ (АВР)</option><option value="invoice">Накладная</option></select></label></div><div class="finance-form-error" id="financeRateError" hidden></div><div class="actions"><button type="button" id="financeRateCancel">Отмена</button><button type="submit" class="primary">Сохранить</button></div></form></dialog>`}
 function docDialog(){if(!canEdit())return"";return`<dialog id="financeDocDialog" class="finance-dialog finance-doc-dialog"><form id="financeDocForm" novalidate><input type="hidden" name="id"><div class="finance-form-head"><div><h2 id="financeDocTitle">Добавить закрывающий документ</h2><p>АВР или накладная по договорным расценкам</p></div><button type="button" class="finance-x" id="financeDocX">×</button></div><div class="finance-doc-meta"><label>Тип документа<select name="doc_type"><option value="avr">Акт выполненных работ (АВР)</option><option value="invoice">Накладная</option></select></label><label>№ документа<input name="number" required placeholder="Например: 5"></label><label>Дата<input type="date" name="date" required></label></div><div class="finance-doc-items-head"><div><b>Позиции документа</b><span>Объём × договорная цена = сумма</span></div><button type="button" id="financeAddItem">＋ Добавить позицию</button></div><div id="financeDocItems" class="finance-doc-items"></div><div class="finance-doc-total"><span>Итого по документу</span><b id="financeDocTotal">0 тг</b></div><div class="finance-form-error" id="financeDocError" hidden></div><div class="actions"><button type="button" id="financeDocCancel">Отмена</button><button type="submit" class="primary">Сохранить документ</button></div></form></dialog>`}
 function summary(allWorks){
  const contract=allWorks.reduce((s,w)=>{const r=rateFor(w.id);return s+(r&&w.plan>0?num(r.price)*w.plan:0)},0),closed=documents().reduce((s,d)=>s+totalDoc(d),0),left=Math.max(0,contract-closed),pct=contract?Math.max(0,Math.min(100,closed/contract*100)):0;
  return`<div class="finance-summary"><div><span>Сумма договора</span><b>${money(contract)}</b><small>По видам работ с заданной ценой</small></div><div><span>Закрыто</span><b>${money(closed)}</b><small>АВР + накладные</small></div><div><span>Осталось закрыть</span><b>${money(left)}</b><small>От договорной стоимости</small></div><div class="finance-progress-card"><div><span>Закрыто</span><b>${Math.round(pct)}%</b></div><i style="--p:${pct.toFixed(2)}"><em></em></i></div></div>`
 }
 function workTable(allWorks){
  const rows=allWorks.map(w=>{const rate=rateFor(w.id),price=rate?num(rate.price):0,cost=price*w.plan,closed=closedAmount(w.id),left=Math.max(0,cost-closed),pct=cost?Math.min(100,closed/cost*100):0,closing=rate?docTypeText(rate.closing_type):"—";return`<div class="finance-work-row"><div><span>Вид работы</span><b>${esc(w.name)}</b><small>${esc(w.code||"Без шифра")}</small></div><div><span>Объём</span><b>${w.plan>0?fmt(w.plan)+" "+esc(w.unit):"—"}</b><small>${w.service?"Услуга":w.marksPlan>w.workPlan?"Из ведомости марок":w.workPlan>0?"Из вида работ":w.marksPlan>0?"Из ведомости марок":""}</small></div><div><span>Цена за 1 ед.</span><b>${rate?money(price):"Не задана"}</b></div><div><span>Стоимость</span><b>${rate&&w.plan>0?money(cost):"—"}</b></div><div><span>Закрыто</span><b>${money(closed)}</b><small>${cost?Math.round(pct)+"%":"—"}</small></div><div><span>Остаток</span><b>${rate&&w.plan>0?money(left):"—"}</b></div><div><span>Документ</span><b>${closing}</b></div>${canEdit()?`<div class="finance-work-actions"><button type="button" data-rate="${w.id}" title="${rate?"Изменить цену":"Указать цену"}">${rate?"Редактировать":"Указать цену"}</button></div>`:"<div></div>"}</div>`}).join("");
  return`<section class="finance-card finance-contract"><div class="finance-card-head"><div><h2>Стоимость по видам работ</h2><p>Объёмы подтягиваются из видов работ и ведомостей марок</p></div></div><div class="finance-work-head"><span>Вид работы</span><span>Объём</span><span>Цена за 1 ед.</span><span>Стоимость</span><span>Закрыто</span><span>Остаток</span><span>Документ</span><span></span></div><div class="finance-work-list">${rows||'<div class="finance-empty">Сначала добавьте виды работ</div>'}</div></section>`
 }
 function docsTable(){
  const docs=documents(),rows=docs.map(d=>{const total=totalDoc(d);return`<div class="finance-doc-row"><div><span>Документ</span><b><i class="finance-doc-badge ${d.doc_type==="invoice"?"invoice":"avr"}">${docTypeText(d.doc_type)}</i> № ${esc(d.number||"—")}</b></div><div><span>Дата</span><b>${dmy(d.date)}</b></div><div><span>Позиций</span><b>${arr(d.items).length}</b></div><div><span>Сумма</span><b>${money(total)}</b></div>${canEdit()?`<div class="finance-doc-actions"><button type="button" data-doc-edit="${d.id}" title="Редактировать">✎</button><button type="button" class="danger" data-doc-delete="${d.id}" title="Удалить">×</button></div>`:"<div></div>"}</div>`}).join("");
  return`<section class="finance-card finance-documents"><div class="finance-card-head"><div><h2>Закрывающие документы</h2><p>Акты выполненных работ и накладные</p></div>${canEdit()?'<button type="button" id="financeAddDoc">＋ Добавить документ</button>':""}</div><div class="finance-doc-head"><span>Документ</span><span>Дата</span><span>Позиций</span><span>Сумма</span><span></span></div><div class="finance-doc-list">${rows||'<div class="finance-empty">Закрывающие документы пока не добавлены</div>'}</div></section>`
 }
 function draw(){
  const works=workTypes();
  app.innerHTML=`<div class="finance-page"><div class="finance-head"><button class="back" id="financeBack">← Назад</button><div><h1>Финансы</h1><p>${esc(object.name||"")}</p></div></div>${summary(works)}${workTable(works)}${docsTable()}${rateDialog()}${docDialog()}</div>`;
  document.getElementById("financeBack").onclick=()=>location.hash=`/objects/object/${oid}`;
  if(canEdit())bind(works);
 }
 function bind(works){
  const rateDialogEl=document.getElementById("financeRateDialog"),rateForm=document.getElementById("financeRateForm"),rateErr=document.getElementById("financeRateError");
  const openRate=wid=>{const w=works.find(x=>x.id===String(wid)),r=rateFor(wid);if(!w)return;rateForm.reset();rateErr.hidden=true;rateForm.elements.id.value=r?.id||"";rateForm.elements.work_type_id.value=w.id;rateForm.elements.price.value=r?.price??"";rateForm.elements.closing_type.value=r?.closing_type||"avr";document.getElementById("financeRateWork").textContent=`${w.name} · ${w.plan?fmt(w.plan)+" "+w.unit:"объём не задан"}`;rateDialogEl.showModal()};
  document.querySelectorAll("[data-rate]").forEach(b=>b.onclick=()=>openRate(b.dataset.rate));
  document.getElementById("financeRateX").onclick=()=>rateDialogEl.close();document.getElementById("financeRateCancel").onclick=()=>rateDialogEl.close();
  rateForm.onsubmit=async e=>{e.preventDefault();rateErr.hidden=true;const fd=new FormData(rateForm),id=String(fd.get("id")||""),wid=String(fd.get("work_type_id")||""),price=num(fd.get("price")),closing=String(fd.get("closing_type")||"avr"),w=works.find(x=>x.id===wid);if(!w||price<=0){rateErr.textContent="Укажите цену за 1 ед. больше 0.";rateErr.hidden=false;return}const payload={record_type:"finance_rate",title:w.name,data:{work_type_id:w.id,work_type:w.name,unit:w.unit,price,closing_type:closing}};if(id)await api.update(id,payload);else await api.create(payload);financeRows=await api.list().catch(()=>financeRows);rateDialogEl.close();draw()};

  const dialog=document.getElementById("financeDocDialog"),form=document.getElementById("financeDocForm"),itemsBox=document.getElementById("financeDocItems"),err=document.getElementById("financeDocError"),docType=form.elements.doc_type;
  const eligible=type=>works.filter(w=>{const r=rateFor(w.id);return r&&r.closing_type===type&&w.plan>0});
  const rowOptions=(type,selected="")=>'<option value="">Выберите вид работы</option>'+eligible(type).map(w=>`<option value="${w.id}" ${String(selected)===w.id?"selected":""}>${esc(w.name)} · ${esc(w.unit)}</option>`).join("");
  const rowHtml=(item={},excludeId="")=>`<div class="finance-doc-item"><label>Вид работы<select name="item_work_type">${rowOptions(docType.value,item.work_type_id||"")}</select></label><label>Объём<input name="item_qty" inputmode="decimal" value="${item.qty??""}" placeholder="0"></label><div class="finance-item-price"><span>Цена</span><b data-item-price>—</b></div><div class="finance-item-amount"><span>Сумма</span><b data-item-amount>0 тг</b><small data-item-left></small></div><button type="button" class="finance-item-remove" title="Удалить позицию">×</button></div>`;
  const refreshTotal=()=>{let total=0;itemsBox.querySelectorAll(".finance-doc-item").forEach(row=>{const wid=String(row.querySelector('[name="item_work_type"]').value||""),qty=num(row.querySelector('[name="item_qty"]').value),r=rateFor(wid),amount=qty*num(r?.price);total+=amount;row.querySelector("[data-item-price]").textContent=r?money(r.price):"—";row.querySelector("[data-item-amount]").textContent=money(amount);const w=works.find(x=>x.id===wid),docId=form.elements.id.value,available=w?Math.max(0,w.plan-closedQty(wid,docId)):0;row.querySelector("[data-item-left]").textContent=w?`Доступно: ${fmt(available)} ${w.unit}`:""}) ;document.getElementById("financeDocTotal").textContent=money(total)};
  const bindItem=row=>{const sel=row.querySelector('[name="item_work_type"]'),qty=row.querySelector('[name="item_qty"]');sel.onchange=refreshTotal;qty.oninput=refreshTotal;row.querySelector(".finance-item-remove").onclick=()=>{row.remove();refreshTotal()};refreshTotal()};
  const addItem=item=>{itemsBox.insertAdjacentHTML("beforeend",rowHtml(item,form.elements.id.value));bindItem(itemsBox.lastElementChild)};
  const refillOptions=()=>{itemsBox.querySelectorAll(".finance-doc-item").forEach(row=>{const s=row.querySelector('[name="item_work_type"]'),old=s.value;s.innerHTML=rowOptions(docType.value,old);if(![...s.options].some(o=>o.value===old))s.value="";s._irSelectUI?.refresh?.()});refreshTotal()};
  const openDoc=d=>{form.reset();itemsBox.innerHTML="";err.hidden=true;form.elements.id.value=d?.id||"";docType.value=d?.doc_type||"avr";form.elements.number.value=d?.number||"";form.elements.date.value=d?.date||new Date().toISOString().slice(0,10);document.getElementById("financeDocTitle").textContent=d?"Редактировать закрывающий документ":"Добавить закрывающий документ";arr(d?.items).forEach(addItem);if(!d?.items?.length)addItem({});dialog.showModal();docType._irSelectUI?.refresh?.();refreshTotal()};
  document.getElementById("financeAddDoc").onclick=()=>openDoc(null);document.querySelectorAll("[data-doc-edit]").forEach(b=>b.onclick=()=>openDoc(documents().find(x=>String(x.id)===String(b.dataset.docEdit))));
  document.querySelectorAll("[data-doc-delete]").forEach(b=>b.onclick=async()=>{const d=documents().find(x=>String(x.id)===String(b.dataset.docDelete));if(!d||!confirm(`Удалить ${docTypeText(d.doc_type)} № ${d.number||"—"} на сумму ${money(totalDoc(d))}?`))return;await api.remove(d.id);financeRows=await api.list().catch(()=>financeRows);draw()});
  document.getElementById("financeDocX").onclick=()=>dialog.close();document.getElementById("financeDocCancel").onclick=()=>dialog.close();document.getElementById("financeAddItem").onclick=()=>addItem({});docType.onchange=refillOptions;
  form.onsubmit=async e=>{e.preventDefault();err.hidden=true;const fd=new FormData(form),id=String(fd.get("id")||""),type=String(fd.get("doc_type")||"avr"),number=String(fd.get("number")||"").trim(),date=String(fd.get("date")||"");if(!number||!date){err.textContent="Укажите номер и дату документа.";err.hidden=false;return}const items=[];for(const row of itemsBox.querySelectorAll(".finance-doc-item")){const wid=String(row.querySelector('[name="item_work_type"]').value||""),qty=num(row.querySelector('[name="item_qty"]').value),w=works.find(x=>x.id===wid),r=rateFor(wid);if(!wid&&!qty)continue;if(!w||!r||r.closing_type!==type||qty<=0){err.textContent="Проверьте вид работы и объём в позициях документа.";err.hidden=false;return}const available=Math.max(0,w.plan-closedQty(wid,id));if(qty>available+1e-9){err.textContent=`По работе «${w.name}» доступно к закрытию ${fmt(available)} ${w.unit}, указано ${fmt(qty)}.`;err.hidden=false;return}items.push({work_type_id:w.id,work_type:w.name,unit:w.unit,qty,price:num(r.price),amount:qty*num(r.price)})}if(!items.length){err.textContent="Добавьте хотя бы одну позицию.";err.hidden=false;return}const payload={record_type:"finance_document",title:`${docTypeText(type)} № ${number}`,data:{doc_type:type,number,date,items}};if(id)await api.update(id,payload);else await api.create(payload);financeRows=await api.list().catch(()=>financeRows);dialog.close();draw()};
 }
 draw();
};