"use strict";
(()=>{
 const esc=v=>String(v??"").replace(/[&<>\"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
 const num=v=>Number(v)||0;
 window.irMarksPage=async oid=>{
  const app=document.getElementById("app"),o=await irProject.data.objects.get(oid),marksApi=irProject.data.forObject(oid).section("marks"),wtApi=irProject.data.forObject(oid).section("work-types");
  let markRows=await marksApi.list().catch(()=>[]),workRows=await wtApi.list().catch(()=>[]),active="all",query="";
  const canEdit=()=>window.irAccess?window.irAccess.canEdit("marks"):false;
  const workTypes=workRows.map(r=>({id:String(r.id),name:r.data?.work_type||r.title||"Без названия",code:r.data?.project_code||"",unit:r.data?.unit||""}));
  const items=()=>markRows.map(x=>({id:x.id,...(x.data||{}),title:x.title||x.data?.title||""}));
  function countFor(id){return items().filter(x=>String(x.work_type_id||"")===String(id)).length}
  function workCards(){return workTypes.map(w=>`<button class="marks-work-card ${active===w.id?"on":""}" data-work="${w.id}"><span class="mwc-title">${esc(w.name)}</span><span class="mwc-code">${esc(w.code||"Шифр не указан")}</span><span class="mwc-meta">${countFor(w.id)} поз. · ${esc(w.unit)}</span>${canEdit()?`<i data-import="${w.id}" title="Загрузить ведомость">＋ Загрузить ведомость</i>`:""}</button>`).join("")}
  function draw(){
   const all=items(),shown=all.filter(x=>(active==="all"||String(x.work_type_id||"")===active)&&(!query||`${x.mark||x.title||""} ${x.name||""}`.toLowerCase().includes(query))),qty=shown.reduce((s,x)=>s+num(x.qty??x.count),0),mounted=shown.reduce((s,x)=>s+Math.min(num(x.qty??x.count),num(x.mounted??x.done)),0),pct=qty?Math.round(mounted/qty*100):0;
   app.innerHTML=`<div class="marks-page"><div class="marks-top"><button class="back" id="marksBack">← Назад</button><div><h1>Ведомость марок</h1><p>${esc(o?.name||"")}</p></div></div><div class="marks-work-types"><div class="marks-work-head"><div><b>Виды работ</b><span>Выберите вид работ для просмотра или загрузки ведомости марок</span></div></div><div class="marks-work-grid"><button class="marks-work-card ${active==="all"?"on":""}" data-work="all"><span class="mwc-title">Все виды работ</span><span class="mwc-code">Общая ведомость</span><span class="mwc-meta">${all.length} позиций</span></button>${workCards()}</div></div><div class="marks-stats">${[["Позиций",shown.length],["По проекту",qty],["Смонтировано",mounted],["Осталось",Math.max(0,qty-mounted)],["Готовность",pct+"%"]].map((x,i)=>`<div class="marks-stat ${i===4?"good":""}"><span>${x[0]}</span><b>${x[1]}</b></div>`).join("")}</div><div class="marks-tools"><input id="marksSearch" value="${esc(query)}" placeholder="Поиск по марке или наименованию…"></div><div class="marks-table"><div class="marks-head"><span>Марка</span><span>Наименование</span><span>Кол-во</span><span>Поступило</span><span>Статус</span><span>Факт монтажа</span><span>%</span><span>Прогресс</span></div>${shown.length?shown.map(x=>{const q=num(x.qty??x.count),d=Math.min(q,num(x.mounted??x.done)),got=num(x.received??x.got),p=q?Math.min(100,Math.round(d/q*100)):0,state=q>0&&d>=q?"done":d>0?"work":"left";return `<div class="marks-row"><b>${esc(x.mark||x.title||"—")}</b><span>${esc(x.name||"")}</span><span>${q}</span><span>${got}</span><span><i class="marks-status ${state}">${state==="done"?"Смонтировано":state==="work"?"В работе":"Не начато"}</i></span><span>${d} / ${q}</span><strong>${p}%</strong><span class="marks-bar ${state}"><i style="width:${p}%"></i></span></div>`}).join(""):'<div class="marks-empty">Для этого вида работ ведомость марок пока не загружена</div>'}</div>${canEdit()?`<dialog id="marksImport" class="marks-import-dialog"><form id="marksImportForm"><input type="hidden" name="work_type_id"><div class="form-heading"><div><h2>Загрузить ведомость марок</h2><p id="marksImportWork" class="form-subtitle"></p></div><button type="button" class="dialog-x" id="marksImportX">×</button></div><p class="marks-import-note">Вставьте строки из Excel. Колонки: <b>Марка | Наименование | Кол-во</b>. Можно копировать диапазон прямо из Excel.</p><textarea name="rows" required placeholder="М1\tКолонна К1\t4\nМ2\tБалка Б1\t8"></textarea><div class="actions"><button type="button" id="marksImportCancel">Отмена</button><button type="submit" class="primary">Загрузить</button></div></form></dialog>`:""}</div>`;
   document.getElementById("marksBack").onclick=()=>location.hash=`/objects/object/${oid}`;
   document.querySelectorAll("[data-work]").forEach(b=>b.onclick=e=>{if(e.target.closest("[data-import]"))return;active=b.dataset.work;draw()});
   const s=document.getElementById("marksSearch");s.oninput=e=>{query=e.target.value.toLowerCase();draw();const n=document.getElementById("marksSearch");n.focus();n.setSelectionRange(n.value.length,n.value.length)};
   if(canEdit()){const d=document.getElementById("marksImport"),f=document.getElementById("marksImportForm");document.querySelectorAll("[data-import]").forEach(b=>b.onclick=e=>{e.stopPropagation();const w=workTypes.find(x=>x.id===b.dataset.import);f.reset();f.elements.work_type_id.value=w.id;document.getElementById("marksImportWork").textContent=`${w.name} · ${w.code} · ${w.unit}`;d.showModal()});document.getElementById("marksImportX").onclick=()=>d.close();document.getElementById("marksImportCancel").onclick=()=>d.close();f.onsubmit=async e=>{e.preventDefault();const fd=new FormData(f),wid=String(fd.get("work_type_id")),w=workTypes.find(x=>x.id===wid),lines=String(fd.get("rows")||"").split(/\r?\n/).map(x=>x.trim()).filter(Boolean);let added=0;for(const line of lines){const c=line.split(/\t|;/).map(x=>x.trim());if(!c[0]||!c[2])continue;const q=Number(String(c[2]).replace(",","."));if(!Number.isFinite(q))continue;await marksApi.create({record_type:"item",title:c[0],data:{work_type_id:wid,work_type:w.name,project_code:w.code,unit:w.unit,mark:c[0],name:c[1]||"",qty:q,mounted:0,received:0}});added++}markRows=await marksApi.list();active=wid;d.close();draw();if(!added)alert("Не найдено строк для загрузки. Используйте колонки: Марка | Наименование | Кол-во")};}
  }
  draw();
 };
})();
