"use strict";
(()=>{
const root=document.getElementById("app");if(!root)return;
const names={reports:"Ежедневные отчёты","work-types":"Виды работ",marks:"Ведомость марок",deliveries:"Поставки",schedule:"График работ",photos:"Фотографии объекта",scheme:"Монтажная схема","acted-days":"Актированные дни",penalties:"Штрафы",finance:"Финансы"};
const icons={overview:"⌂",reports:"▤","work-types":"≡",marks:"▦",deliveries:"⇩",schedule:"⌁",photos:"▧",scheme:"⌘","acted-days":"□",penalties:"!",finance:"₸"};
let scheduled=false,serial=0;
const routeInfo=()=>{const r=location.hash.slice(1)||"/objects";const m=r.match(/^\/objects\/object\/(\d+)(?:\/([^/]+))?/);return m?{id:m[1],key:m[2]||"overview"}:null};
function button(label,key,active,disabled,onClick){const b=document.createElement("button");b.type="button";b.disabled=!!disabled;b.className=active?"active":"";const i=document.createElement("span");i.className="nav-icon";i.textContent=icons[key]||"•";const t=document.createElement("span");t.textContent=label;b.append(i,t);if(!disabled)b.onclick=onClick;return b}
async function brand(aside){const host=aside.querySelector(".ir-object-brand");if(!host)return;try{const p=await irProject.company.get()||{};if(p.logo){const u=await irProject.images.read(p.logo);if(u){const im=document.createElement("img");im.src=u;im.alt=p.name||"Логотип компании";host.replaceChildren(im);return}}const s=document.createElement("span");s.textContent=p.name||"IR Project";host.replaceChildren(s)}catch{const s=document.createElement("span");s.textContent="IR Project";host.replaceChildren(s)}}
async function nav(aside,info,token){let sections=[];try{sections=await irProject.data.sections.get(info.id)||[]}catch{}if(token!==serial||!document.body.contains(aside))return;const n=aside.querySelector(".ir-object-nav");if(!n)return;n.replaceChildren();n.append(button("Обзор","overview",info.key==="overview",false,()=>location.hash=`/objects/object/${info.id}`));for(const s of sections){const key=s.section_key,label=s.title||names[key]||key;n.append(button(label,key,info.key===key,!s.enabled,()=>location.hash=`/objects/object/${info.id}/${encodeURIComponent(key)}`))}}
async function apply(){scheduled=false;const info=routeInfo();if(!info){root.classList.remove("ir-object-shell-host");return}if(root.querySelector(":scope > .ir-object-shell"))return;const token=++serial;const nodes=[...root.childNodes];if(!nodes.length)return;root.classList.add("ir-object-shell-host");const shell=document.createElement("div");shell.className="ir-object-shell";const aside=document.createElement("aside");aside.className="ir-object-sidebar";aside.innerHTML='<div class="ir-object-brand"><span>IR Project</span></div><button class="ir-object-all" type="button"><span>‹</span><b>Все объекты</b></button><nav class="ir-object-nav"></nav><button class="ir-object-top" type="button"><span>↑</span><b>Наверх</b></button>';const main=document.createElement("main");main.className="ir-object-main"+(info.key==="overview"?" ir-overview-content":"");for(const node of nodes)main.appendChild(node);shell.append(aside,main);root.appendChild(shell);aside.querySelector(".ir-object-all").onclick=()=>location.hash="/objects";aside.querySelector(".ir-object-top").onclick=()=>window.scrollTo({top:0,behavior:"smooth"});brand(aside);nav(aside,info,token)}
function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(apply)}
new MutationObserver(schedule).observe(root,{childList:true});window.addEventListener("hashchange",schedule);schedule();
})();
