"use strict";
(()=>{
 const names={admin:"Администратор",engineer:"Инженер ПТО",guest:"Гость"};
 const sectionNames={reports:"Ежедневные отчеты","work-types":"Виды работ",marks:"Ведомость марок",schedule:"График работ",photos:"Фотографии объекта",scheme:"Монтажная схема","acted-days":"Актированные дни",penalties:"Штрафы",finance:"Финансы"};
 function sectionFromHash(){const m=location.hash.match(/^#\/objects\/object\/\d+\/([^/]+)$/);return m?m[1]:null}
 function editable(){const r=irAccess.role();if(r==="admin")return true;if(r==="guest")return false;const section=sectionFromHash();return section?irAccess.canEdit(section):false}
 function apply(){document.querySelectorAll("[data-access-lock]").forEach(x=>x.removeAttribute("data-access-lock"));const role=irAccess.role(),can=editable();document.querySelectorAll("#add,#photoButton,#bannerButton,[data-toggle]").forEach(el=>{if(role!=="admin"){el.disabled=true;el.setAttribute("data-access-lock","1")}});if(!can&&sectionFromHash())document.querySelectorAll("button").forEach(el=>{if(!el.classList.contains("back")&&!el.closest(".profile-panel")){el.disabled=true;el.setAttribute("data-access-lock","1")}});const badge=document.getElementById("profileBadge");if(badge)badge.textContent=names[role];const settings=document.getElementById("engineerSettings");if(settings)settings.hidden=role!=="admin";const select=document.getElementById("roleSelect");if(select)select.value=role;}
 async function switchRole(next){if(next==="guest"){irAccess.setRole("guest");apply();return true}const label=names[next];const password=prompt(`Введите пароль профиля «${label}»:`);if(password===null)return false;let ok=false;try{ok=await irProject.access.login(next,password)}catch(e){alert("Не удалось проверить пароль.");return false}if(!ok){alert("Неверный пароль.");return false}irAccess.setRole(next);apply();return true}
 function panel(){const old=document.querySelector(".profile-panel");if(old)old.remove();const p=document.createElement("div");p.className="profile-panel";p.innerHTML=`<button id="profileBadge" class="profile-badge">${names[irAccess.role()]}</button><div id="profileMenu" class="profile-menu" hidden><label>Профиль<select id="roleSelect"><option value="admin">Администратор</option><option value="engineer">Инженер ПТО</option><option value="guest">Гость</option></select></label><button id="engineerSettings" hidden>Доступ инженера</button></div>`;document.body.appendChild(p);const badge=p.querySelector("#profileBadge"),menu=p.querySelector("#profileMenu"),select=p.querySelector("#roleSelect"),settings=p.querySelector("#engineerSettings");select.value=irAccess.role();badge.onclick=()=>menu.hidden=!menu.hidden;select.onchange=async()=>{const requested=select.value;await switchRole(requested);select.value=irAccess.role();menu.hidden=true};settings.onclick=()=>permissions();apply();}
 function permissions(){if(irAccess.role()!=="admin"){alert("Настройки доступа изменяет только администратор.");return}const current=irAccess.engineer();const d=document.createElement("dialog");d.className="permissions-dialog";d.innerHTML=`<h2>Доступ инженера ПТО</h2><p>Отметьте разделы, которые инженер ПТО может изменять. Остальные доступны только для просмотра.</p><div class="permission-list">${irAccess.KEYS.map(k=>`<label><input type="checkbox" data-perm="${k}" ${current[k]?"checked":""}>${sectionNames[k]}</label>`).join("")}</div><div class="actions"><button id="permClose">Готово</button></div>`;document.body.appendChild(d);d.querySelectorAll("[data-perm]").forEach(x=>x.onchange=()=>irAccess.setEngineer(x.dataset.perm,x.checked));d.querySelector("#permClose").onclick=()=>{d.close();d.remove()};d.showModal()}
 const observer=new MutationObserver(()=>apply());observer.observe(document.getElementById("app"),{childList:true,subtree:true});window.addEventListener("hashchange",()=>setTimeout(apply,0));sessionStorage.setItem("ir-role","guest");panel();apply();
})();
