"use strict";
const { app } = require("electron");
const fs = require("fs");
const path = require("path");
const https = require("https");
const crypto = require("crypto");
const { EventEmitter } = require("events");
const OWNER="ispayevibr-ship-it",REPO="ir-project";
const events=new EventEmitter();let available=null;
const root=()=>path.join(app.getPath("userData"),"app-updates");
const current=()=>path.join(root(),"current");
const manifestFile=()=>path.join(current(),"hot-manifest.json");
function request(url,asJson=false){return new Promise((resolve,reject)=>{const go=u=>https.get(u,{headers:{"User-Agent":"IR-Project-Updater","Cache-Control":"no-cache, no-store, must-revalidate","Pragma":"no-cache","Accept":asJson?"application/json":"*/*"}},res=>{if(res.statusCode>=300&&res.statusCode<400&&res.headers.location){res.resume();return go(res.headers.location)}if(res.statusCode!==200){res.resume();return reject(new Error(`HTTP ${res.statusCode}: ${u}`))}const chunks=[];res.on("data",c=>chunks.push(c));res.on("end",()=>{const data=Buffer.concat(chunks);if(!asJson)return resolve(data);try{resolve(JSON.parse(data.toString("utf8")))}catch(e){reject(e)}})}).on("error",reject);go(url)})}
function hash(data){return crypto.createHash("sha256").update(data).digest("hex")}
function installedVersion(){try{const m=JSON.parse(fs.readFileSync(manifestFile(),"utf8"));if(!m.version||!Array.isArray(m.files))throw 0;for(const f of m.files){const p=path.join(current(),f.target);if(!fs.existsSync(p))throw 0;if(f.sha256&&hash(fs.readFileSync(p))!==f.sha256)throw 0}return m.version}catch{return app.getVersion()}}
function newer(a,b){const A=String(a).split(".").map(Number),B=String(b).split(".").map(Number);for(let i=0;i<Math.max(A.length,B.length);i++){const x=A[i]||0,y=B[i]||0;if(x!==y)return x>y}return false}
async function check(){available=null;const m=await request(`https://raw.githubusercontent.com/${OWNER}/${REPO}/main/hot/latest.json?ir=${Date.now()}`,true);const local=installedVersion();if(newer(m.version,local)){available=m;events.emit("update-available",{version:m.version,size:(m.files||[]).reduce((s,f)=>s+(Number(f.size)||0),0),installedVersion:local});return {updateInfo:{version:m.version}}}events.emit("update-not-available",{version:local,remoteVersion:m.version});return {updateInfo:{version:local}}}
async function downloadUpdate(){if(!available){await check();if(!available)throw new Error("Обновление не найдено")};const stage=path.join(root(),"staging");fs.rmSync(stage,{recursive:true,force:true});fs.mkdirSync(stage,{recursive:true});const verified=[];const files=available.files||[];const expected=files.reduce((s,f)=>s+(Number(f.size)||0),0)||1;let done=0;for(const f of files){const data=await request(`https://raw.githubusercontent.com/${OWNER}/${REPO}/main/${f.source}?ir=${Date.now()}-${Math.random()}`,false);const dest=path.join(stage,f.target);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,data);const saved=fs.readFileSync(dest);if(!saved.length)throw new Error(`Пустой файл обновления: ${f.target}`);verified.push({...f,size:saved.length,sha256:hash(saved)});done+=saved.length;events.emit("download-progress",{percent:Math.min(100,Math.round(done/Math.max(expected,done)*100)),transferred:done,total:Math.max(expected,done),bytesPerSecond:0})}fs.writeFileSync(path.join(stage,"hot-manifest.json"),JSON.stringify({version:available.version,installedAt:new Date().toISOString(),files:verified},null,2));for(const f of verified){const p=path.join(stage,f.target);if(!fs.existsSync(p)||hash(fs.readFileSync(p))!==f.sha256)throw new Error(`Проверка файла не пройдена: ${f.target}`)}fs.rmSync(current(),{recursive:true,force:true});fs.renameSync(stage,current());if(installedVersion()!==available.version)throw new Error("Обновление скачано, но проверка установленной версии не пройдена");events.emit("update-downloaded",{version:available.version});return [current()]}
function install(){app.relaunch();app.exit(0)}
module.exports={check,download:downloadUpdate,install,updater:events,currentDir:current,installedVersion};
