"use strict";
const { app }=require("electron");
const fs=require("fs"),path=require("path"),https=require("https"),crypto=require("crypto");
const {EventEmitter}=require("events");
const OWNER="ispayevibr-ship-it",REPO="ir-project";
const events=new EventEmitter();let available=null;
const root=()=>path.join(app.getPath("userData"),"app-updates");
const current=()=>path.join(root(),"current");
const stage=()=>path.join(root(),"staging");
const manifestFile=dir=>path.join(dir,"hot-manifest.json");
function compare(a,b){const A=String(a||"0").split(".").map(Number),B=String(b||"0").split(".").map(Number);for(let i=0;i<Math.max(A.length,B.length);i++){const d=(A[i]||0)-(B[i]||0);if(d)return d>0?1:-1}return 0}
function hash(data){return crypto.createHash("sha256").update(data).digest("hex")}
function request(url,json=false){return new Promise((resolve,reject)=>{const go=u=>https.get(u,{headers:{"User-Agent":"IR-Project-Updater/2","Cache-Control":"no-cache, no-store, must-revalidate","Pragma":"no-cache","Accept":json?"application/json":"*/*"}},res=>{if(res.statusCode>=300&&res.statusCode<400&&res.headers.location){res.resume();return go(res.headers.location)}if(res.statusCode!==200){res.resume();return reject(new Error(`HTTP ${res.statusCode}: ${u}`))}const chunks=[];res.on("data",c=>chunks.push(c));res.on("end",()=>{const b=Buffer.concat(chunks);if(!json)return resolve(b);try{resolve(JSON.parse(b.toString("utf8")))}catch(e){reject(new Error(`Некорректный manifest: ${e.message}`))}})}).on("error",reject);go(url)})}
function readManifest(dir=current()){try{return JSON.parse(fs.readFileSync(manifestFile(dir),"utf8"))}catch{return null}}
function verifyRuntime(dir=current()){const m=readManifest(dir);if(!m?.version||!Array.isArray(m.files)||!m.files.length)return null;for(const f of m.files){const p=path.join(dir,f.target);if(!fs.existsSync(p))return null;const b=fs.readFileSync(p);if(!b.length)return null;if(f.sha256&&hash(b)!==f.sha256)return null}const entry=path.join(dir,"src","index.html");return fs.existsSync(entry)?m:null}
function installedVersion(){const m=verifyRuntime();return m&&compare(m.version,app.getVersion())>0?m.version:app.getVersion()}
async function check(){available=null;const url=`https://raw.githubusercontent.com/${OWNER}/${REPO}/main/hot/latest.json?ir=${Date.now()}-${Math.random()}`;const m=await request(url,true);if(!m?.version||!Array.isArray(m.files))throw new Error("Manifest обновления имеет неверный формат");const local=installedVersion();const info={baseVersion:app.getVersion(),installedVersion:local,remoteVersion:m.version,url};if(compare(m.version,local)>0){available=m;events.emit("update-available",{...info,version:m.version,size:m.files.reduce((s,f)=>s+(Number(f.size)||0),0)});return {updateInfo:{version:m.version},diagnostics:info}}events.emit("update-not-available",{...info,version:local});return {updateInfo:{version:local},diagnostics:info}}
async function downloadUpdate(){if(!available){await check();if(!available)throw new Error("Обновление не найдено")};const dir=stage();fs.rmSync(dir,{recursive:true,force:true});fs.mkdirSync(dir,{recursive:true});const files=available.files,verified=[],expected=files.reduce((s,f)=>s+(Number(f.size)||0),0)||1;let done=0;for(const f of files){const data=await request(`https://raw.githubusercontent.com/${OWNER}/${REPO}/main/${f.source}?ir=${Date.now()}-${Math.random()}`);const dest=path.join(dir,f.target);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,data);const b=fs.readFileSync(dest);if(!b.length)throw new Error(`Пустой файл: ${f.target}`);verified.push({source:f.source,target:f.target,size:b.length,sha256:hash(b)});done+=b.length;events.emit("download-progress",{percent:Math.min(100,Math.round(done/Math.max(expected,done)*100)),transferred:done,total:Math.max(expected,done),bytesPerSecond:0})}fs.writeFileSync(manifestFile(dir),JSON.stringify({version:available.version,installedAt:new Date().toISOString(),files:verified},null,2));if(!verifyRuntime(dir))throw new Error("Hot-runtime неполный или повреждён");fs.rmSync(current(),{recursive:true,force:true});fs.renameSync(dir,current());if(installedVersion()!==available.version)throw new Error("Версия после установки не совпала с manifest");events.emit("update-downloaded",{version:available.version});return [current()]}
function install(){app.relaunch();app.exit(0)}
module.exports={check,download:downloadUpdate,install,updater:events,currentDir:current,installedVersion,verifyRuntime};
